spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/${PGDATABASE}
    username: ${PGUSER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
